#include <stdio.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

struct fn {
	const char* lib;
	char* func;
};

struct fn fns[256];
char lib_buf[1024];

uint32_t hash(const unsigned char* str){
	uint32_t hash = 6159;
	for(;; ++str){
		hash = hash * (-69) + *str;
		if(!*str) break;
	}
	return hash;
}

int main(void){
	char line[256];

	char* lib = lib_buf;
	char* lib_next = lib;

	struct fn* fn = fns;

	while(fgets(line, sizeof(line), stdin)){
		line[strcspn(line, "\r\n")] = 0;

		if(*line == '/'){
			lib = lib_next;
			lib_next = stpcpy(lib, line+1) + 1;
		} else {

			if(lib == lib_next){
				fprintf(stderr, "error: function specified before any libs\n");
				return 1;
			}
			*fn++ = (struct fn){ lib, strdup(line) };
		}
	}

	puts("# generated by fngen\n\n.data\n\nfn_loader_data:");

	int count = 0;
	for(struct fn* f = fns; f < fn; ++f){
		bool samelib = (count == 0 || f[0].lib == f[-1].lib);

		if(samelib)
			++count;
		
		if(!samelib || fn - f == 1){
			printf("\t.byte %d\n\t.asciz \"%s\"\n", count, f[-1].lib);
			count = 1;
		}
	}
	puts("\t.byte 0");

	puts("\nfn_table:");
	for(struct fn* f = fns; f < fn; ++f){
		printf("\t.int %#08x # %s\n", hash(f->func), f->func);
	}

	puts("");
	for(struct fn* f = fns; f < fn; ++f){
		printf("\t.equ _fn_%s, %ld\n", f->func, (f - fns) * 4);
	}

	puts("\n\t.equ FN_LOADER_SIZE, fn_table - fn_loader_data");

	return 0;
}
